apiVersion: v1
kind: Service
metadata:
  name: shopwise-app-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: my-ecomm-azure
spec:
  type: LoadBalancer
  selector:
    app: shopwise-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
