apiVersion: v1
kind: Service
metadata:
  name: backend-manfacturer-app-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: my-azure-ecomm
spec:
  type: LoadBalancer
  selector:
    app: manufacturer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
