apiVersion: v1
kind: Service
metadata:
  name: backend-shopclues-app-service
spec:
  selector:
    app: backend-shopclues-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
