apiVersion: v1
kind: Service
metadata:
  name: backend-shopclues-app-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: my-azure-ecomm
spec:
  type: LoadBalancer
  selector:
    app: shopclues
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
