apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-shopclues-app
  labels:
    app: backend-shopclues-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-shopclues-app
  template:
    metadata:
      labels:
        app: backend-shopclues-app
    spec:
      containers:
        - name: backend-shopclues-app
          image: ecommazureacr.azurecr.io/shopclues-backend:latest
          ports:
            - containerPort: 8080
