apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopclues-app
  labels:
    app: shopclues-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopclues-app
  template:
    metadata:
      labels:
        app: shopclues-app
    spec:
      containers:
        - name: shopclues-app
          image: ecommazureacr.azurecr.io/shopclues-frontend:latest
          ports:
            - containerPort: 80
