name: Deploy to AKS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Azure Container Registry (if used)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Step 4: Build and push Docker images
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/myapp:latest .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/myapp:latest

      # Step 5: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      # Step 6: Log in to Azure CLI
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 7: Get AKS credentials
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

      # Step 8: Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
