name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin

      - name: Validate directory structure
        run: |
          echo "Validating directory structure..."
          ls -la
          ls -la Backend-Java-Spring
          ls -la Frontend-Angular

      - name: Build ShopClues Microservice
        run: |
          cd Backend-Java-Spring/ShopClues
          mvn clean package

      - name: Build ShopClues Frontend Application
        run: |
          cd Frontend-Angular/ShopClues
          npm install
          npm run build

      - name: Build Docker Images and Push to ACR
        env:
          AZURE_ACR_LOGIN_SERVER: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          AZURE_ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
          AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
        run: |
          # ShopClues Microservice
          cd Backend-Java-Spring/ShopClues
          docker build --no-cache -t shopclues-backend .
          docker tag shopclues-backend:latest $AZURE_ACR_LOGIN_SERVER/shopclues-backend-service:latest

          # ShopClues Frontend
          cd ../../Frontend-Angular/ShopClues
          docker build --no-cache -t shopclues-frontend .
          docker tag shopclues-frontend:latest $AZURE_ACR_LOGIN_SERVER/shopclues-frontend-service:latest


          # Login to ACR
          echo $AZURE_ACR_PASSWORD | docker login $AZURE_ACR_LOGIN_SERVER -u $AZURE_ACR_USERNAME --password-stdin

          # Push Docker Images
          docker push $AZURE_ACR_LOGIN_SERVER/shopclues-backend-service:latest
          docker push $AZURE_ACR_LOGIN_SERVER/shopclues-frontend-service:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        run: |
          az aks get-credentials --resource-group ecomm-azure-resourcegroup --name ecomm-azure-aks-cluster

      - name: Deploy to AKS Cluster
        run: |
          # Apply Kubernetes deployment and service files for ShopClues Microservice
          cd Backend-Java-Spring/ShopClues
          kubectl apply -f shopclues-deployment.yaml
          kubectl apply -f service.yaml

          # Apply Kubernetes deployment and service files for ShopClues Frontend
          cd ../../Frontend-Angular/ShopClues
          kubectl apply -f shopclues-frontend-deployment.yaml
          kubectl apply -f service.yaml
